<h1>Atividade 03 - CCF493</h1>     

<h3>Nome: Vítor Luís G. Silva</h3> 
<h3>Matrícula: 3045</h3>

In [1]:
import warnings
import itertools
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn import tree
from sklearn import metrics
from sklearn.cluster import KMeans
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import classification_report
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

warnings.filterwarnings('ignore')

In [6]:
def classifier(X_train, X_test, Y_train, Y_test):
    # Aplicando KNN
    print("[KNN]")
    knn=KNeighborsClassifier()
    knn.fit(X_train,Y_train)
    print(classification_report(Y_test, knn.predict(X_test)))
    print()
    
    # Aplicando Naive Bayes
    print("[Naive Bayes]")
    nb=BernoulliNB()
    nb.fit(X_train,Y_train)
    print(classification_report(Y_test, nb.predict(X_test)))
    print()
    
    #Aplicando Arvore de Decisao
    print("[Árvore de Decisão]")
    dtc=tree.DecisionTreeClassifier()
    dtc.fit(X_train,Y_train)
    print(classification_report(Y_test, dtc.predict(X_test)))

In [17]:
def transform_to_binary(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

<h2>Churn</h2>

In [13]:
# Leitura do arquivo csv
df = pd.read_csv('./data/churn-telecom.csv')

# Remoção de dados inválido
df = df.dropna()

df.head()

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [14]:
# Converter atributos binários que são strings
df = df.replace(['no'], 0)
df = df.replace(['yes'], 1)

# Converter atributos binário que são booleanos
df = df.replace([True], 1)
df = df.replace([False], 0)

# Remover campo com os estados e número
df.drop('state', axis='columns', inplace=True)
df.drop('phone number', axis='columns', inplace=True)

df.head()

,account length,area code,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,total eve minutes,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,128,415,0,1,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,107,415,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,137,415,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,84,408,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,75,415,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0

In [16]:
# Remoção da coluna churn
df_without_churn = df.drop('churn', axis='columns', inplace=False)

# Treino do algoritmo
X_train, X_test, Y_train, Y_test = train_test_split(df_without_churn, df['churn'], test_size=0.2, random_state=0)

# Execução dos classificadores
classifier(X_train,X_test,Y_train,Y_test)

[KNN]
              precision    recall  f1-score   support

           0       0.89      0.97      0.93       579
           1       0.51      0.22      0.30        88

    accuracy                           0.87       667
   macro avg       0.70      0.59      0.62       667
weighted avg       0.84      0.87      0.85       667


[Naive Bayes]
              precision    recall  f1-score   support

           0       0.88      0.96      0.92       579
           1       0.38      0.15      0.21        88

    accuracy                           0.86       667
   macro avg       0.63      0.56      0.57       667
weighted avg       0.82      0.86      0.83       667


[Árvore de Decisão]
              precision    recall  f1-score   support

           0       0.97      0.91      0.94       579
           1       0.58      0.78      0.67        88

    accuracy                           0.90       667
   macro avg       0.77      0.85      0.80       667
weighted avg       0.91      0.90      0.90       667

In [23]:
# Transformar 'number vmail messages' em atributo binário
result = [transform_to_binary(x) for x in df['number vmail messages']]

df_modified = df
df_modified['number vmail messages'] = result

df_modified.head()

,account length,area code,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,total eve minutes,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,128,415,0,1,1,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,107,415,0,1,1,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,137,415,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,84,408,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,75,415,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0

In [24]:
# Remoção da coluna churn
df_modified_without_churn = df_modified.drop('churn', axis='columns', inplace=False)

# Treino do algoritmo
X_train, X_test, Y_train, Y_test = train_test_split(df_modified_without_churn, df_modified['churn'], test_size=0.2, random_state=0)

# Execução dos classificadores
classifier(X_train,X_test,Y_train,Y_test)

[KNN]
              precision    recall  f1-score   support

           0       0.89      0.97      0.93       579
           1       0.53      0.20      0.30        88

    accuracy                           0.87       667
   macro avg       0.71      0.59      0.61       667
weighted avg       0.84      0.87      0.85       667


[Naive Bayes]
              precision    recall  f1-score   support

           0       0.88      0.96      0.92       579
           1       0.38      0.15      0.21        88

    accuracy                           0.86       667
   macro avg       0.63      0.56      0.57       667
weighted avg       0.82      0.86      0.83       667


[Árvore de Decisão]
              precision    recall  f1-score   support

           0       0.97      0.92      0.94       579
           1       0.59      0.80      0.68        88

    accuracy                           0.90       667
   macro avg       0.78      0.86      0.81       667
weighted avg       0.92      0.90      0.91       667

<strong>Análise</strong>

Mudar o atributo 'number vmail messages' para binário não modificou os resultados.

<h2>Heart</h2>

In [28]:
# Leitura do arquivo csv
df = pd.read_csv('./data/heart.csv')

# Remoção de dados inválido
df = df.dropna()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [29]:
# Remoção da coluna churn
df_without_target = df.drop('target', axis='columns', inplace=False)

# Treino do algoritmo
X_train, X_test, Y_train, Y_test = train_test_split(df_without_target, df['target'], test_size=0.2, random_state=0)

# Execução dos classificadores
classifier(X_train,X_test,Y_train,Y_test)

[KNN]
              precision    recall  f1-score   support

           0       0.59      0.63      0.61        27
           1       0.69      0.65      0.67        34

    accuracy                           0.64        61
   macro avg       0.64      0.64      0.64        61
weighted avg       0.64      0.64      0.64        61


[Naive Bayes]
              precision    recall  f1-score   support

           0       0.83      0.74      0.78        27
           1       0.81      0.88      0.85        34

    accuracy                           0.82        61
   macro avg       0.82      0.81      0.81        61
weighted avg       0.82      0.82      0.82        61


[Árvore de Decisão]
              precision    recall  f1-score   support

           0       0.70      0.78      0.74        27
           1       0.81      0.74      0.77        34

    accuracy                           0.75        61
   macro avg       0.75      0.76      0.75        61
weighted avg       0.76      0.75      0.75        61